name: Actualizar Avisos AEMET

on:
  schedule:
    - cron: "*/10 * * * *"  # Cada 10 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de procesamiento
        run: python procesar_geojson.py

      - name: Commit y push si hay cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add avisos_espana.geojson
          git commit -m "Actualización automática del GeoJSON" || exit 0
          git push
