name: Update AEMET Alerts

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python extraccion.py

      # List files in the directory to check if GeoJSON file exists
      - name: List files in the directory
        run: |
          echo "Listing files in the directory"
          ls -l

      # Verify if the file exists and then commit
      - name: Check if GeoJSON file exists and commit changes
        run: |
          if [ -f "aemet_alerts.geojson" ]; then
            echo "GeoJSON file exists, proceeding with commit."
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add aemet_alerts.geojson
            git commit -m "Update AEMET alerts data" || exit 0
            git push
          else
            echo "GeoJSON file does not exist."
            exit 1
